### ISSUE TITLE
mixed dungeon/raid icon shows as a green box

### ISSUE THREAD

**Issue by rursache** [belazor-wow/WorldDungeonLocations#13]
### Description

amazing addon exactly what i needed however the mixed dungeon/raid icon shows as a green box: https://i.imgur.com/CXnbZeT.png

### World of Warcraft Flavor

Retail (Default)

### WorldDungeonLocations Version

v2.0.0 (latest curseforge)

### Tested with only WorldDungeonLocations

Yes

### Reproduction Steps

enable addon and check the map

### Screenshots

https://i.imgur.com/CXnbZeT.png

**Comment by Numynum** [comment]
does it keep happening after restarting the game?

**Comment by rursache** [comment]
it got fixed indeed after restarting the game!
